const SET_VISIBILITY = 'SET_VISIBILITY';
const ADD_POPUP = 'ADD_POPUP';
const SAVE_POPUP = 'SAVE_POPUP';
const DELETE_POPUP = 'DELETE_POPUP';
const SELECT_POPUP = 'SELECT_POPUP';
const CLEAR_VIEW = 'CLEAR_VIEW';
const UPDATE_FIELD = 'UPDATE_FIELD';
const ADD_RULE = 'ADD_RULE';
const REMOVE_RULE = 'REMOVE_RULE';
const UPDATE_RULE = 'UPDATE_RULE';


export {
  SET_VISIBILITY,
  ADD_POPUP,
  SAVE_POPUP,
  DELETE_POPUP,
  SELECT_POPUP,
  CLEAR_VIEW,
  UPDATE_FIELD,
  ADD_RULE,
  REMOVE_RULE,
  UPDATE_RULE
};
