const SET_VISIBILITY = 'SET_VISIBILITY';
const ADD_POPUP = 'ADD_POPUP';
const SAVE_POPUP = 'SAVE_POPUP';
const UPDATE_POPUPS = 'UPDATE_POPUPS';
const SET_SAVE_SUCCESS = 'SET_SAVE_SUCCESS';
const SET_DATA = 'SET_DATA';
const SET_SAVE_ERROR = 'SET_SAVE_ERROR';
const SET_DEL_SUCCESS = 'SET_DEL_SUCCESS';
const SET_DEL_ERROR = 'SET_DEL_ERROR';
const DELETE_POPUP = 'DELETE_POPUP';
const SELECT_POPUP = 'SELECT_POPUP';
const CLEAR_VIEW = 'CLEAR_VIEW';
const UPDATE_FIELD = 'UPDATE_FIELD';
const ADD_RULE = 'ADD_RULE';
const REMOVE_RULE = 'REMOVE_RULE';
const UPDATE_RULE = 'UPDATE_RULE';


export {
  SET_VISIBILITY,
  ADD_POPUP,
  SAVE_POPUP,
  UPDATE_POPUPS,
  SET_SAVE_SUCCESS,
  SET_DATA,

  SET_SAVE_ERROR,
  SET_DEL_SUCCESS,
  SET_DEL_ERROR,
  DELETE_POPUP,
  SELECT_POPUP,
  CLEAR_VIEW,
  UPDATE_FIELD,
  ADD_RULE,
  REMOVE_RULE,
  UPDATE_RULE
};
